### ISSUE TITLE
关于 huile8-ecdict 的数据库

### ISSUE THREAD

**Issue by mqycn** [w88975/code-translate-vscode#1]
我是 huile8 的作者，在 v2ex 看到 你在帖子 https://v2ex.com/t/704380 中提到了我。

在这里 我要提下，[huile8](https://github.com/mqycn/huile8) 的数据库 不是 sqlite，是json格式的文件，通过 [huile8-ecdict](https://github.com/mqycn/huile8-ecdict) 执行 npm run make 生成 json格式的词库，相关代码：

https://github.com/mqycn/huile8-ecdict/blob/2dfd5188df9472fbe6e59899a133b1a4994d9f97/huile8-tools/make.js#L20-L59

最后分享下我的小心得：

最早我考虑过 csv文件，大文件操作内存占用太恐怖。

后来改成了 Sqlite3，然后遇到了新问题，跨平台有问题。

最后改成了 json 格式的数据，并将词库问单词前两个字母 分到多个json，最大的词库文件659KB

比如单词absolute，在ab.json，这样能减少内存占用

另外的一处优化，我对查询结果增加了一层缓存：https://github.com/mqycn/huile8/issues/3#issuecomment-685490680

我在 后期也会加选词功能，有点类似，可不是抄袭你的哦~

我的思路和你的不太一样：还是在左侧陌生单词列表显示，只不过只分析选中部分的单词。

**Comment by w88975** [comment]
多谢建议 
最开始我也是sqlite，发现打包后过不了，也考虑过跨平台可能会有问题。

暂未找到轻量级的本地数据库跨平台方案，所以就用csv逐行检索的方式，这样内存占用小，但是时间跨度长，试过也就1s左右 所以就没太折腾了

至于说功能抄袭 这个大可不必😂 我也是抄的浏览器端的滑词翻译创意 
反正还是多谢你的建议👍

**Comment by mqycn** [comment]
OK，以后多交流~👍👍
