### ISSUE TITLE
在打包的时候会报错

### ISSUE THREAD

**Issue by LinForGame** [w88975/code-translate-vscode#11]
code-translate-vscode\package.json 文件中 第28行 "browser": "./dist/web/extension.js", 不知道是做什么的，在打包的时候会报错，删掉就好了，大佬有空看下~
ERROR Extension entrypoint(s) missing. Make sure these files exist and aren't ignored by '.vscodeignore':
extension/dist/web/extension.js

**Comment by w88975** [comment]
这个是打包web扩展的，vscode online想用该插件，得专门打包一个web版本
