### ISSUE TITLE
Migrate to translate.google.com

### ISSUE THREAD

**Issue by YuruiHong** [w88975/code-translate-vscode#8]
As google translate is no longer available as `translate.google.cn`, I think that it is better to migrate to the original `translate.google.com` so that people using proxies may get access to it. Just simply making substitutions in `./src/index.js` worked for me.

**Comment by w88975** [comment]
已修复: https://github.com/w88975/code-translate-vscode/commit/06fb6c170c781e509422605faf5f00188be6bdfc
